version: '3'

services:

  dbpostgres:
    image: postgres:16
    container_name: ex_db
    networks:
      - note
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata_note:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true


  redis:
      image: "redis/redis-stack:7.4.0-v0"
      container_name: ex_redis
      networks:
        - note
      env_file:
        - .env
      volumes:
        - redisdata_note:/data
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M

      healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 1s
        timeout: 3s
        retries: 5
      restart: unless-stopped
      tty: true
      stdin_open: true


  rabbitmq:
    image: rabbitmq:4.0.0-rc.1-management-alpine
    container_name: ex_rabbit
    hostname: rabbitmq
    networks:
      - note
    restart: always
    configs:
      - source: rabit_config
        target: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - rabbitdata_note:/var/lib/rabbitmq

  auth_server:
    build: .
    container_name: ex_auth
    networks:
      - note
    env_file:
      - .env
      - .celery.env
      - .email.env
      - .secret.env
      - .logging.env
    depends_on:
      - ex_db
      - ex_redis
      - ex_rabbit
    ports:
      - 8000:8000

  celery_worker:
    build: .
    container_name: ex_celery
    entrypoint: uv run celery -A src.email_celery.router worker --loglevel=INFO
    networks:
      - note
    env_file:
      - .env
      - .celery.env
      - .email.env
      - .secret.env
    depends_on:
      - ex_auth
      - ex_db
      - ex_redis
      - ex_rabbit

  flower:
    build: .
    container_name: ex_flower
    entrypoint: uv run celery -A src.email_celery.router flower --port=8002
    networks:
      - note
    env_file:
      - .env
      - .celery.env
      - .email.env
      - .secret.env
    depends_on:
      - ex_auth
      - ex_db
      - ex_redis
      - ex_rabbit
    ports:
      - 8002:8002

volumes:
  rabbitdata_note:
  redisdata_note:
  postgresdata_note:

configs:
  rabit_config:
    file: ./config_container/rabitmq.conf


networks:
  note:
    name: note
    driver: bridge
